# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('sirmvit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('address', models.CharField(db_index=True, max_length=200)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[300, 300], upload_to='products/%Y/%m/%d')),
                ('USN', models.TextField(blank=True)),
                ('first', models.DecimalField(decimal_places=2, max_digits=10)),
                ('second', models.DecimalField(decimal_places=2, max_digits=10)),
                ('third', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fourth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fifth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sirmvit.Category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='Studentdb',
        ),
        migrations.AlterIndexTogether(
            name='studentdbs',
            index_together=set([('id', 'slug')]),
        ),
    ]
