# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirmvit', '0003_auto_20180319_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdbs',
            name='USN',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
