# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirmvit', '0004_auto_20180319_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdbs',
            options={'ordering': ('USN',)},
        ),
    ]
