# Generated by Django 2.0.7 on 2018-07-25 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirmvit', '0005_auto_20180320_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdbs',
            name='image',
        ),
        migrations.AlterField(
            model_name='studentdbs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='sirmvit.Category'),
        ),
    ]
