# Generated by Django 2.0.7 on 2018-07-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirmvit', '0006_auto_20180725_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdbs',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
