# Generated by Django 2.0.7 on 2018-11-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirmvit', '0008_auto_20180726_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdbs',
            old_name='critical_research',
            new_name='information_management_system',
        ),
        migrations.RenameField(
            model_name='studentdbs',
            old_name='data_analysis',
            new_name='machine_learning',
        ),
        migrations.RenameField(
            model_name='studentdbs',
            old_name='domain',
            new_name='software_architecture',
        ),
        migrations.RenameField(
            model_name='studentdbs',
            old_name='general_biology',
            new_name='unix',
        ),
        migrations.RenameField(
            model_name='studentdbs',
            old_name='quality_control',
            new_name='web_tech',
        ),
    ]
